# Generated by Django 2.0.7 on 2020-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Democharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('wand', models.TextField(blank=True, null=True)),
                ('patronus', models.TextField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('blood_status', models.TextField(blank=True, null=True)),
                ('hair_colour', models.TextField(blank=True, null=True)),
                ('eye_colour', models.TextField(blank=True, null=True)),
                ('loyalty', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('birth', models.TextField(blank=True, null=True)),
                ('death', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models_democharacters',
            },
        ),
        migrations.CreateModel(
            name='Demopotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('known_ingredients', models.TextField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models_demopotions',
            },
        ),
        migrations.CreateModel(
            name='Demospells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('incantation', models.TextField(blank=True, null=True)),
                ('spell_type', models.TextField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('light', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models_demospells',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='ModelsCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('house', models.CharField(blank=True, max_length=200, null=True)),
                ('wand', models.CharField(blank=True, max_length=200, null=True)),
                ('patronus', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_status', models.CharField(blank=True, max_length=200, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=200, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=200, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models_characters',
            },
        ),
        migrations.CreateModel(
            name='ModelsPotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', models.TextField()),
                ('effect', models.CharField(blank=True, max_length=200, null=True)),
                ('characteristics', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'models_potions',
            },
        ),
        migrations.CreateModel(
            name='ModelsSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('incantation', models.CharField(blank=True, max_length=200, null=True)),
                ('spell_type', models.CharField(blank=True, max_length=200, null=True)),
                ('effect', models.CharField(blank=True, max_length=200, null=True)),
                ('light', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'models_spell',
            },
        ),
    ]
